### ISSUE TITLE
Need's updating

### ISSUE THREAD

**Issue by NuLogicSystems** [wfx/epack#6]
Epack no longer runs under EFL 1.18.0:

DEVELOPER WARNING:
        Using subprocess (Popen and derivatives) with Ecore is a bad idea.

        Ecore will set some signal handlers subprocess module depends and this
        may cause this module to operate unexpectedly.

        Instead of using subprocess.Popen(), please consider using Ecore's
        Exe() class.
        
  File "/usr/bin/epack", line 31, in <module>
    from epack.backend import load_backend
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3.5/site-packages/epack/backend.py", line 29, in <module>
    from epack.backend_shell import ShellBackend
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3.5/site-packages/epack/backend_shell.py", line 21, in <module>
    import magic
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3.5/site-packages/magic.py", line 20, in <module>
    _libraries['magic'] = _init()
  File "/usr/lib/python3.5/site-packages/magic.py", line 17, in _init
    return ctypes.cdll.LoadLibrary(find_library('magic'))
  File "/usr/lib/python3.5/ctypes/util.py", line 240, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/usr/lib/python3.5/ctypes/util.py", line 232, in _findSoname_ldconfig
    env={'LC_ALL': 'C', 'LANG': 'C'}) as p:
cannot import name 'mime_type_query' - Shell backend disabled
Traceback (most recent call last):
  File "/usr/bin/epack", line 147, in <module>
    app = EpackApplication(args)
  File "/usr/bin/epack", line 51, in __init__
    self.main_win = MainWin(self)
  File "/usr/lib/python3.5/site-packages/epack/gui.py", line 151, in __init__
    self.update_ui()
  File "/usr/lib/python3.5/site-packages/epack/gui.py", line 202, in update_ui
    ic = Icon(box, standard='dialog-info', size_hint_min=(24,24))
  File "efl/elementary/icon.pxi", line 38, in efl.elementary.__init__.Icon.__init__ (efl/elementary/__init__.c:156140)
  File "efl.evas_object.pxi", line 209, in efl.evas.Object._set_properties_from_keyword_args (efl/evas/efl.evas.c:51748)
  File "efl.eo.pyx", line 276, in efl.eo.Eo._set_properties_from_keyword_args (efl/eo/efl.eo.c:3446)
  File "efl/elementary/icon.pxi", line 109, in efl.elementary.__init__.Icon.standard.__set__ (efl/elementary/__init__.c:156737)
RuntimeWarning: Setting standard icon failed

**Comment by DaveMDS** [comment]
hmm, I do not get this error here with efl 1.18.0
the problem is that on your system efl cannot find the 'dialog-info' icon.

I changed the icon name to 'dialog-information' that is more correct and also made epack not fail if an icon is not found.

Can you please retry and confirm this is solved also for you? please also check that the "info" icon show up in the top-right corner.

and also: are you using a non-efl icon theme?

**Comment by NuLogicSystems** [comment]
Yes, that fixed the issue, it's now launching as it should.

I'm using EFL built from the stable branch (efl-1.18) of git.
I did set the system to use the new Enlightenment-x icon theme that comes with EFL 1.18.
I always enable both Applications and Enlightenment to use the icon theme selected under application theme settings. If that is what caused the issue then from a user standpoint that would not be good, just saying. Anyway, keep up the great work, the more EFL applications the better.

Egitu has the same issue with icons, I'll check to see if disabling those settings fix it or not.

**Comment by NuLogicSystems** [comment]
Nope, changing the icon settings made no difference.
PS: I don't mess with the EFL source code, I just download, build, and install it.
The same goes for python-efl.
